config/routes.rb
Rails.application.routes.draw do
  resources :years
  resources :programs

  post '/auth/:provider/callback' => 'sessions#create'
  get '/auth/destroy' => 'sessions#destroy', as: 'destroy_session'

  resources :users, only: %w{index show}
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/program.rb
class Program < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :year
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_auth_hash(auth)
    oauth_email = auth["info"]["email"] 
    oauth_name = auth["info"]["name"] || auth["info"]["nickname"]
    self.where(email: oauth_email).first_or_create do |u|
      u.name = oauth_name
    end
  end
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :programs

  def to_param
    return nil unless persisted?
    self.year.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_for_user

  def current_user
    @current_user ||= if session[:user_id]
      User.find(session[:user_id])
    else
      nil
    end
  end

  def super_admin?
    current_user && current_user.super_admin
  end

  def check_for_user
    redirect_to root_path, error: 'Please log in first.' unless current_user
  end

  def check_for_super_admin
    redirect_to root_path, error: "You can't go there." unless super_admin?
  end

  helper_method :current_user, :super_admin?
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: %i[ show edit update destroy ]
  before_action :check_for_super_admin

  # GET /programs or /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1 or /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs or /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to program_url(@program), notice: "Program was successfully created." }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1 or /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to program_url(@program), notice: "Program was successfully updated." }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1 or /programs/1.json
  def destroy
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url, notice: "Program was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def program_params
      params.require(:program).permit(:name, :color, :slug)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create
  skip_before_action :check_for_user, only: :create

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    check_for_super_admin
    
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :check_for_user
  
  def index
    if current_user
      render :dashboard
    else
      render :index
    end
  end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  before_action :set_year, only: %i[ show edit update destroy ]

  # GET /years or /years.json
  def index
    @years = Year.all
  end

  # GET /years/1 or /years/1.json
  def show
    @year = Year.find_by(year: params[:id])
  end

  # GET /years/new
  def new
    @year = Year.new
  end

  # GET /years/1/edit
  def edit
  end

  # POST /years or /years.json
  def create
    @year = Year.new(year_params)

    respond_to do |format|
      if @year.save
        format.html { redirect_to year_url(@year), notice: "Year was successfully created." }
        format.json { render :show, status: :created, location: @year }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /years/1 or /years/1.json
  def update
    respond_to do |format|
      if @year.update(year_params)
        format.html { redirect_to year_url(@year), notice: "Year was successfully updated." }
        format.json { render :show, status: :ok, location: @year }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /years/1 or /years/1.json
  def destroy
    @year.destroy

    respond_to do |format|
      format.html { redirect_to years_url, notice: "Year was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_year
      puts Year.find_by(year: params[:id]).inspect
      @year = Year.find_by(year: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def year_params
      params.require(:year).permit(:year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def contrasting_color(color)
    base = Color::RGB.by_hex(color)
    if base.brightness > 0.5
      '#000'
    else
      '#fff'
    end
  end
end

app/helpers/font_awesome_helper.rb
module FontAwesomeHelper
  def font_awesome_kit_url
    ENV['FONT_AWESOME_URL'] || 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/js/all.min.js'
  end

  def icon(icon, variant="s", options={})
    opts = {
      variant: 's'
    }.merge(options).with_indifferent_access
    content_tag(:i, '', class: [
      'fa-fw',
      "fa#{opts['variant']}",
      "fa-#{icon}",
      *options
      ])
  end
end

app/helpers/program_helper.rb
module ProgramHelper
  def program_badge(program)
    classes = 'badge rounded-pill program-badge'
    style = "background-color: #{program.color}; color: #{contrasting_color program.color}; text-decoration: none"

    content_tag :span, program.name, class: classes, style: style
  end
end

app/helpers/year_helper.rb
module YearHelper
  def year_badge(y)
    classes = "badge rounded-pill year-badge"
    style = "background-color: #9a989a; color: black;"

    content_tag :span, "20#{y.year - 1} - #{y.year}", class: classes, style: style
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FIN Central</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag font_awesome_kit_url %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.5.1.js' %>
    <%= javascript_include_tag 'https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js' %>
    <%= javascript_include_tag 'https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js' %>
  </head>

  <body class="bg-light">
    <%= render partial: 'components/navbar' %>

    <%= render partial: 'components/subnav' %>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/programs/_form.html.erb
<%= simple_form_for(@program) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs row">
    <div class="col-8">
      <%= f.input :name %>
    </div>
    <div class="col-4">
      <%= f.input :color, as: "color" %>
    </div>
  </div>

  <div class="form-actions row">
    <div class="col-10"></div>
    <div class="col-2">
      <%= f.button :submit, class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/programs/_program.html.erb
<div id="<%= dom_id program %>">
  <div class="row my-2">
    <div class="col-3">
      <%= link_to program_badge(program), program %>
    </div>
  </div>
</div>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render "form", program: @program %>

<br>

<div>
  <%= link_to "Show this program", @program %> |
  <%= link_to "Back to programs", programs_path %>
</div>

app/views/programs/index.html.erb
<h1>Programs</h1>

<div id="programs">
  <% @programs.each do |program| %>
    <%= render program %>
  <% end %>
</div>

<%= link_to "New program", new_program_path %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render "form", program: @program %>

<br>

<div>
  <%= link_to "Back to programs", programs_path %>
</div>

app/views/programs/show.html.erb
<h1><%= program_badge @program %></h1>

<div class="position-absolute bottom-0 w-50">
  <div class="row my-2">
    <div class="col-3">
      <%= link_to "Edit this program", edit_program_path(@program), class: "btn btn-warning" %>
    </div>
    <div class="col-3">
      <%= button_to "Destroy this program", @program, method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/users/_badges.html.erb
<% if user.super_admin %>
    <span class="badge bg-dark"><%= icon 'hat-wizard' %> Super Admin</span>
<% end %>

app/views/users/index.html.erb
<h1>All Registered Users</h1>

<table class="datatable table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Affiliations</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <td>
        <%= link_to user.name, user %>
      </td>
      <td><%= link_to user.email, "mailto:#{user.email}" %></td>
      <td>
        <%= render partial: 'badges', locals: { user: user } %>
      </td>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div class="row">
  <div class="col-6">
    <h2>Affiliations</h2>
    <%= render partial: 'badges', locals: { user: @user } %>
  </div>
  <div class="col-6">
    <%= link_to "Send Email", "mailto:#{@user.email}", class: 'btn btn-primary' %>
  </div>
</div>

app/views/welcome/dashboard.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <h2 class="card-header">Hi, <%= current_user.name %></h5>
      <div class="card-body">
        
      </div>
    </div>
  <div>

  <div class="col-md-6">
  </div>

  <div class="col-md-2">
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-8">
  </div>
  <div class="col-md-4">
    <h2>Log In</h2>
    <%= link_to '/auth/developer', class: 'btn btn-outline-dark btn-block btn-lg my-3', data: { turbo: false } do %>
      <%= icon('laptop') %> Log in as Developer
    <% end %>
  </div>
</div>

app/views/years/_form.html.erb
<%= simple_form_for(@year) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :year %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/years/_year.html.erb
<div id="<%= dom_id year %>">
  <div class="row my-2">
    <div class= "col-3">
      <%= link_to year_badge(year), year %>
    </div>
  </div>
</div>

app/views/years/edit.html.erb
<h1>Editing year</h1>

<%= render "form", year: @year %>

<br>

<div>
  <%= link_to "Show this year", @year %> |
  <%= link_to "Back to years", years_path %>
</div>

app/views/years/index.html.erb
<h1>Years</h1>

<div id="years">
  <% @years.each do |year| %>
    <%= render year %>
  <% end %>
</div>

<%= link_to "New year", new_year_path %>

app/views/years/new.html.erb
<h1>New year</h1>

<%= render "form", year: @year %>

<br>

<div>
  <%= link_to "Back to years", years_path %>
</div>

app/views/years/show.html.erb
<h1><%= year_badge @year %></h1>

<div class="position-absolute bottom-0 w-50">
  <div class="row my-2">
    <div class="col-3">
      <%= link_to "Edit this year", edit_year_path(@year), class: 'btn btn-warning' %>
    </div>
    <div class="col-3">
      <%= button_to "Destroy this year", @year, method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
</div>